In [14]:
import numpy as np
#numpy tutorial
data=[4,5,76,3,-5.6,"a"]
data_np= np.array(data)
print(data_np)
print(type(data),type(data_np),data_np.dtype)

['4' '5' '76' '3' '-5.6' 'a']
<class 'list'> <class 'numpy.ndarray'> <U32


In [15]:
print(data_np.shape)
print(data_np.ndim)


(6,)
1


In [17]:
print(np.zeros((2,4))) #multidim array((x,y)), single dim(x)
print(np.ones((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
print(np.empty((2,2)))

[[3.24033371e-312 1.89145368e-307]
 [6.89796323e-307 4.45042952e-307]]


In [20]:
np.arange(13) #range func

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
np.ones_like(data_np) #uses an aray as sample, zeros_like

array(['1', '1', '1', '1', '1', '1'], dtype='<U32')

In [29]:
print(np.eye(3,4)) #identity matrix


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [35]:
arr=np.array(([2,3,5.6,4],[-0.4,3,5,0]),dtype=np.int32)
print(arr,arr.dtype) #rounds float to int

[[2 3 5 4]
 [0 3 5 0]] int32


In [36]:
#astype method, change array type
array=np.array([1,2,3,4,5])
print(array.dtype)
f_array=array.astype(np.float64)
print(f_array.dtype)

int32
float64


In [38]:
#string to float
arr=np.array(["3","4","9.8"],dtype=np.string_)
f_arr=arr.astype(np.float64)
print(f_arr,f_arr.dtype)

[3.  4.  9.8] float64
